### ISSUE TITLE
Feature request: Template out certs.yaml file

### ISSUE THREAD

**Issue by aaron-prindle** [SUSE/helm-certgen#20]
I have a certs.yaml with the following structure:

```
name: tls-webhook-secret
metadata:
  name: tls-webhook-secret-name
spec:
  api:
    name: tls-webhook-secret-cert
    csr:
      country: US
      state: CA
      locality: Mountain View
      organisationname: foo
    hosts:
    - foo-validation-hook
    - foo-validation-hook.kube-system
    - foo-validation-hook.default
    - foo-validation-hook.default.svc
```
I would like `default` here to be configurable with something like:
`{{ service.Namespace }}`

but I am not sure how to do something like this using only helm and the certgen plugin
